export enum SaveDisabledEnums {
  EDIT_CERTIFICATE = 'EDIT_CERTIFICATE',
  SAVE_CERTIFICATE = 'SAVE_CERTIFICATE',
  INPUT_FILE = 'INPUT_FILE',
  INPUT_MULTY_IMAGE = 'INPUT_MULTY_IMAGE',
  INPUT_MULTY_VIDEO = 'INPUT_MULTY_VIDEO',
}
