export enum ModalEnums {
  ADD_COUNTRY = 'ADD_COUNTRY',
  EDIT_COUNTRY = 'EDIT_COUNTRY',
  ADD_CITY = 'ADD_CITY',
  EDIT_CITY = 'EDIT_CITY',
  ADD_CEMETERY = 'ADD_CEMETERY',
  EDIT_CEMETERY = 'EDIT_CEMETERY',
  ADD_TRIBUTE = 'ADD_TRIBUTE',
  EDIT_TRIBUTE = 'EDIT_TRIBUTE',
  ADD_GETHERING = 'ADD_GETHERING',
  EDIT_GETHERING = 'EDIT_GETHERING',
}
