export const ROUTE_NAMES = {
  index: '/',
  dashboard: '/dashboard',
  countries: '/countries',
  leads: '/leads',
  convertLead: '/convert-lead/:id',
  cities: '/cities',
  cemeteries: '/cemeteries',
  orderes: '/orderes',
  getherings: '/getherings',
  qrcodes: '/qrcodes',
  previews: '/previews',
  tributes: '/tributes',
  newCerificate: '/new-certificate',
  newCerificateManagement: '/new-certificate-management',
  certificates: '/certificates',
  certificateById: '/certificates/:id',
  firtTimeRegister: '/first-time-register/:token',
  createCertificate: '/create-certificate/:token',
  signUp: '/sign-up',
  blogs: '/blogs',
  blogById: '/blogs/:id',
  contacts: '/contacts',
  profile: '/profile',
  notFound: '/not-found',
}
